version = 0.1

[qa_assignmentevent_stream]
[qa_assignmentevent_stream.deploy]
[qa_assignmentevent_stream.deploy.parameters]
stack_name = "qaAssignmenteventKinesisStack"
resolve_s3 = true
s3_prefix = "qaAssignmenteventKinesisStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "InputStreamName=\"qa_assignmentevent_stream\" TargetStreamReplicationRegion=\"us-west-2\" SNSTopic=\"monitor-issues\""
image_repositories = []
disable_rollback = false

[qa_locationradius_stream]
[qa_locationradius_stream.deploy]
[qa_locationradius_stream.deploy.parameters]
stack_name = "qalocationradiusKinesisStack"
resolve_s3 = true
s3_prefix = "qalocationradiusKinesisStack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "InputStreamName=\"qa_locationradius_stream\" TargetStreamReplicationRegion=\"us-west-2\" SNSTopic=\"monitor-issues\""
image_repositories = []
disable_rollback = false

[prod_assignmentevent_stream]
[prod_assignmentevent_stream.deploy]
[prod_assignmentevent_stream.deploy.parameters]
stack_name = "prodAssignmenteventKinesisStack"
resolve_s3 = true
s3_prefix = "prodAssignmenteventKinesisStack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "InputStreamName=\"prod_assignmentevent_stream\" TargetStreamReplicationRegion=\"us-west-2\" SNSTopic=\"monitorCriticalIssues\""
image_repositories = []
disable_rollback = false

[prod_locationradius_stream]
[prod_locationradius_stream.deploy]
[prod_locationradius_stream.deploy.parameters]
stack_name = "prodlocationradiusKinesisStack"
resolve_s3 = true
s3_prefix = "prodlocationradiusKinesisStack"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "InputStreamName=\"prod_locationradius_stream\" TargetStreamReplicationRegion=\"us-west-2\" SNSTopic=\"monitorCriticalIssues\""
image_repositories = []
disable_rollback = false